import type { ArtKey, Card, Level, Tile } from "./types.ts";

const card = (
  id: string,
  name: string,
  art: ArtKey,
  ports: number[],
  extras: Partial<Card> = {},
): Card => ({
  id,
  name,
  art,
  ports,
  locked: false,
  stamp: false,
  echo: null,
  ...extras,
});

const pin = (id: string, name: string, art: ArtKey, ports: number[]) =>
  card(id, name, art, ports, { locked: true });

const pose = (id: string, rotation = 0): Tile => ({ id, rotation });

// Directions are clockwise: north=0, east=1, south=2, west=3.
// Each solution is authored; it is a witness, not a uniqueness claim.
export const LEVELS: Level[] = [
  {
    id: "first-turn",
    title: "A turn for the better",
    place: "The little lighthouse",
    columns: 2,
    letter: "Dear wanderer,\nThe shortest road is sometimes a quarter turn away.",
    lesson: "Select the lighthouse, then turn it. Roads must meet at the edges.",
    hint: "The lighthouse wants a road to the west and one to the south.",
    start: "home",
    goal: "mail",
    requiredEchoes: [],
    cards: [
      pin("home", "Departure", "home", [1]),
      card("light", "Little lighthouse", "lighthouse", [0, 1], { stamp: true }),
      card("garden", "Quiet garden", "garden", []),
      pin("mail", "Delivery", "mail", [0]),
    ],
    initial: [pose("home"), pose("light"), pose("garden"), pose("mail")],
    solution: [pose("home"), pose("light", 2), pose("garden"), pose("mail")],
  },
  {
    id: "places-trade",
    title: "Places trade places",
    place: "The upside-down windmill",
    columns: 3,
    letter: "Dear wanderer,\nThe windmill moved next door. The neighbours barely noticed.",
    lesson: "Tap two unpinned postcards to swap them. You can also drag one onto another.",
    hint: "Build the top row: departure → windmill → observatory. Then turn south.",
    start: "home",
    goal: "mail",
    requiredEchoes: [],
    cards: [
      pin("home", "Departure", "home", [1]),
      card("mill", "Upside-down windmill", "windmill", [1, 3], { stamp: true }),
      card("stars", "Pocket observatory", "observatory", [2, 3], {
        stamp: true,
      }),
      card("garden", "Quiet garden", "garden", []),
      card("cloud", "Cloud orchard", "orchard", []),
      pin("mail", "Delivery", "mail", [0]),
    ],
    initial: [
      pose("home"),
      pose("stars"),
      pose("mill", 1),
      pose("garden"),
      pose("cloud"),
      pose("mail"),
    ],
    solution: [
      pose("home"),
      pose("mill"),
      pose("stars"),
      pose("garden"),
      pose("cloud"),
      pose("mail"),
    ],
  },
  {
    id: "scenic-route",
    title: "Take the scenic route",
    place: "The rainhouse",
    columns: 3,
    letter: "Dear wanderer,\nWe took the long way home. It had better flowers.",
    lesson:
      "Visit every postage stamp before delivery. A short route is not always the right route.",
    hint: "Try a U-shaped journey: down from home, across the bottom, then up to delivery.",
    start: "home",
    goal: "mail",
    requiredEchoes: [],
    cards: [
      pin("home", "Departure", "home", [2]),
      card("cloud", "Cloud orchard", "orchard", []),
      pin("mail", "Delivery", "mail", [2]),
      card("light", "Little lighthouse", "lighthouse", [0, 1], { stamp: true }),
      card("rain", "Rainhouse", "greenhouse", [1, 3], { stamp: true }),
      card("stars", "Pocket observatory", "observatory", [0, 3], {
        stamp: true,
      }),
    ],
    initial: [
      pose("home"),
      pose("rain", 1),
      pose("mail"),
      pose("stars", 2),
      pose("cloud"),
      pose("light", 1),
    ],
    solution: [
      pose("home"),
      pose("cloud"),
      pose("mail"),
      pose("light"),
      pose("rain"),
      pose("stars"),
    ],
  },
  {
    id: "elsewhere-door",
    title: "A door to elsewhere",
    place: "The twin archways",
    columns: 3,
    letter: "Dear wanderer,\nTwo doors agreed on north. Suddenly, far away was next door.",
    lesson: "Matching echo doors connect across space when their arrows point the same way.",
    hint: "The two blue doors have to agree on a direction. One beside home, one beside delivery.",
    start: "home",
    goal: "mail",
    requiredEchoes: ["blue"],
    cards: [
      pin("home", "Departure", "home", [1]),
      card("arch-a", "Near archway", "arch", [3], {
        stamp: true,
        echo: "blue",
      }),
      card("cloud", "Cloud orchard", "orchard", []),
      card("garden", "Quiet garden", "garden", []),
      card("arch-b", "Far archway", "arch", [1], { stamp: true, echo: "blue" }),
      pin("mail", "Delivery", "mail", [3]),
    ],
    initial: [
      pose("home"),
      pose("arch-a", 1),
      pose("cloud"),
      pose("garden"),
      pose("arch-b", 2),
      pose("mail"),
    ],
    solution: [
      pose("home"),
      pose("arch-a"),
      pose("cloud"),
      pose("garden"),
      pose("arch-b"),
      pose("mail"),
    ],
  },
  {
    id: "detour-in-blue",
    title: "A detour in blue",
    place: "The floating teahouse",
    columns: 3,
    letter: "Dear wanderer,\nThe tea was warm. The sea between the doors was optional.",
    lesson:
      "Roads and echo doors belong to the same journey. Collect all four stamps and use the blue echo.",
    hint: "Home → lighthouse → blue door. The other blue door → teahouse → delivery.",
    start: "home",
    goal: "mail",
    requiredEchoes: ["blue"],
    cards: [
      pin("home", "Departure", "home", [1]),
      card("light", "Little lighthouse", "lighthouse", [1, 3], { stamp: true }),
      card("arch-a", "Near archway", "arch", [3], {
        stamp: true,
        echo: "blue",
      }),
      card("arch-b", "Far archway", "arch", [1], { stamp: true, echo: "blue" }),
      card("tea", "Floating teahouse", "teahouse", [1, 3], { stamp: true }),
      pin("mail", "Delivery", "mail", [3]),
    ],
    initial: [
      pose("home"),
      pose("tea", 1),
      pose("arch-b", 1),
      pose("light", 2),
      pose("arch-a", 3),
      pose("mail"),
    ],
    solution: [
      pose("home"),
      pose("light"),
      pose("arch-a"),
      pose("arch-b"),
      pose("tea"),
      pose("mail"),
    ],
  },
  {
    id: "two-fold-world",
    title: "The twice-folded world",
    place: "The impossible post office",
    columns: 3,
    letter: "Dear wanderer,\nI folded the world twice. Your letter arrived without a crease.",
    lesson: "Join both echo pairs and collect every stamp. Each echo can be used once per journey.",
    hint: "Home → lighthouse → blue echo → observatory → coral echo → delivery. The empty gardens are breathing room.",
    start: "home",
    goal: "mail",
    requiredEchoes: ["blue", "coral"],
    cards: [
      pin("home", "Departure", "home", [1]),
      card("light", "Little lighthouse", "lighthouse", [1, 3], { stamp: true }),
      card("arch-a", "Near blue arch", "arch", [3], {
        stamp: true,
        echo: "blue",
      }),
      card("arch-b", "Far blue arch", "arch", [1], {
        stamp: true,
        echo: "blue",
      }),
      card("stars", "Pocket observatory", "observatory", [1, 3], {
        stamp: true,
      }),
      card("rose-a", "Near coral arch", "arch", [3], {
        stamp: true,
        echo: "coral",
      }),
      card("cloud", "Cloud orchard", "orchard", []),
      card("rose-b", "Far coral arch", "arch", [1], {
        stamp: true,
        echo: "coral",
      }),
      pin("mail", "Delivery", "mail", [3]),
    ],
    initial: [
      pose("home"),
      pose("stars", 1),
      pose("rose-b", 2),
      pose("arch-a", 2),
      pose("cloud"),
      pose("arch-b", 1),
      pose("light", 3),
      pose("rose-a", 1),
      pose("mail"),
    ],
    solution: [
      pose("home"),
      pose("light"),
      pose("arch-a"),
      pose("arch-b"),
      pose("stars"),
      pose("rose-a"),
      pose("cloud"),
      pose("rose-b"),
      pose("mail"),
    ],
  },
];

export const compass = ["north", "east", "south", "west"];
